### ISSUE TITLE
Update the comments of the output dimensions for the vid_to_imgs function

### ISSUE THREAD

**Issue by yenchiah** [CMU-CREATE-Lab/optical-flow#2]
The output dimensions of the vid_to_imgs give (36, 180, 180, 3), which is (time, height, width, channel). Can you update the comments in the code to reflect this setting, please? Thanks.

Note that you do not need to change the code to make it (channel, time, height, width). Updating the comments is sufficient.

**Comment by SeanPrendi** [comment]
Solved. Comments have been updated to reflect the output of the vid_to_imgs function and the batch_optical_flow function.
